# Generated by Django 3.2.7 on 2021-09-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=220)),
                ('nationality', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['id'],
            },
        ),
    ]
